version: '3.9'
services:
  api1:
    build: ./api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db
    networks:
      - backend

  api2:
    build: ./api
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db
    networks:
      - backend

  frontend-react:
    build: ./frontend-react
    ports:
      - "3000:80"
    networks:
      - frontend

  frontend-blazor:
    build: ./frontend-blazor
    ports:
      - "5003:80"
    networks:
      - frontend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api1
      - api2
      - frontend-react
      - frontend-blazor
    networks:
      - frontend
      - backend

  nbomber:
    build: ./tests/nbomber
    depends_on:
      - api1
      - api2
    networks:
      - backend

  k6:
    build: ./tests/k6
    depends_on:
      - api1
      - api2
    networks:
      - backend

  zap:
    build: ./tests/zap
    depends_on:
      - api1
      - api2
    networks:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: nftuser
      POSTGRES_PASSWORD: nftpass
      POSTGRES_DB: nftshop
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  frontend:
  backend:
